version: "3"

services:

    webapp:
        build:
            context: .
            dockerfile: webapp.Dockerfile

    proxy:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - "80"
        