version: "3"

services:

  gateway:
    build:
      context: ./nginx
    depends_on:
      - front-end
      - back-end
    ports:
      - "80:80"

  front-end:
    build:
      context: ./front-end
  
  back-end:
    build:
      context: ./back-end
    depends_on:
      - redis
  
  redis:
    image: redis:latest

    