version: "3"

services:

  gateway:
    build:
      context: ./nginx
    depends_on:
      - front-end
      - back-end
    ports:
      - 80:80
    restart: always

  front-end:
    build:
      context: ./front-end
    restart: always
  
  back-end:
    build:
      context: ./back-end
    depends_on:
      - redis
    restart: always
  
  redis:
    image: redis:latest
    restart: always

    